source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TNSwiftyCheckboxGroup_Example', :exclusive => true do
  pod "TNSwiftyCheckboxGroup", :path => "../"
end

target 'TNSwiftyCheckboxGroup_Tests', :exclusive => true do
  pod "TNSwiftyCheckboxGroup", :path => "../"

  
end
